export const articles = [
  {
    id: 'sistema-captacion-inteligente',
    title: 'No vendemos páginas web: implementamos sistemas de captación',
    category: 'Estrategia',
    slug: 'sistema-captacion-inteligente',
    readTime: 7,
    excerpt: 'Un sitio web no alcanza. Un chatbot aislado no alcanza. Lo que convierte es un sistema integrado: web + IA + WhatsApp + CRM. Esto es el Sistema Verano.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'sistema-vs-piezas',
    title: 'Páginas web, redes, SEO y CRM por separado vs. un solo sistema',
    category: 'Modelo de negocio',
    slug: 'sistema-vs-piezas',
    readTime: 7,
    excerpt: 'Comprar herramientas sueltas genera costos duplicados, puntos de falla y pobre coordinación. Un sistema integrado busca un solo objetivo: conseguir clientes sin perder oportunidades.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'web-ia-whatsapp-crm-rd',
    title: 'Cómo implementar un sistema 24/7 sin levantar una sola llamada',
    category: 'Captación',
    slug: 'web-ia-whatsapp-crm-rd',
    readTime: 6,
    excerpt: 'Web de alta conversión, chatbot con IA, atención por WhatsApp y CRM organizado. Flujo real en República Dominicana para clínicas e inmobiliarias.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'kpis-sistema-captacion',
    title: 'Métricas que importan en un sistema de captación (no las vanidades)',
    category: 'Analítica',
    slug: 'kpis-sistema-captacion',
    readTime: 7,
    excerpt: 'Visitas, likes y clics no pagan el sueldo. Estos son los KPIs que permiten saber si tu sistema está captando, atendiendo y cerrando clientes.',
    date: 'Agosto 2026',
    published: true,
  },
  {
    id: 'seo-local-inmo-clinicas',
    title: 'SEO local para clínicas e inmobiliarias: de Google Maps a llamada real',
    category: 'SEO Local',
    slug: 'seo-local-inmo-clinicas',
    readTime: 6,
    excerpt: 'Aparecer en Google Maps no es suficiente. Este es el flujo para transformar búsquedas locales en leads cualificados dentro de un sistema.',
    date: 'Agosto 2026',
    published: true,
  },
]

export type Article = typeof articles[0]
