export const articles = [
  {
    id: 'landing-vs-sitio',
    title: 'Landing page vs sitio web: la decision que muchos negocios toman mal',
    category: 'Diseno Web',
    slug: 'landing-vs-sitio',
    readTime: 7,
    excerpt: 'No es lo mismo un local en un mall que una boutique en una calle tranquila. Tu sitio web tampoco deberia serlo.',
    date: 'Mayo 2026',
    published: true,
  },
  {
    id: 'chatbots-whatsapp',
    title: 'Chatbots en WhatsApp: como funcionan y cuanto puedes ahorrar',
    category: 'Automatizacion',
    slug: 'chatbots-whatsapp',
    readTime: 6,
    excerpt: 'Tu cliente pregunta a las 11 de la noche. Un chatbot responde. Tu te despiertas con un lead calificado.',
    date: 'Junio 2026',
    published: true,
  },
  {
    id: 'tu-negocio-no-aparece-en-google-maps',
    title: 'Tu negocio no aparece en Google Maps? Esto es lo que estas haciendo mal',
    category: 'SEO Local',
    slug: 'tu-negocio-no-aparece-en-google-maps',
    readTime: 7,
    excerpt: 'Si tu negocio no aparece cuando alguien busca "dentista cerca de mi", no es culpa de Google. Es culpa tuya.',
    date: 'Junio 2026',
    published: true,
  },
  {
    id: 'cm-vs-publicidad',
    title: 'Community Management vs Publicidad: que necesita tu negocio primero?',
    category: 'Redes Sociales',
    slug: 'cm-vs-publicidad',
    readTime: 7,
    excerpt: 'Uno construye confianza a largo plazo. El otro vende hoy. La mayoria de los negocios elige mal porque no entiende la diferencia.',
    date: 'Junio 2026',
    published: true,
  },
  {
    id: 'google-meta-ads',
    title: 'Google Ads vs Meta Ads: cuando invertir y como no perder dinero',
    category: 'Anuncios',
    slug: 'google-meta-ads',
    readTime: 8,
    excerpt: 'Invertir en anuncios sin estrategia es como prender fuego a tu presupuesto.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'automatizacion-pymes',
    title: 'Automatizacion para pequenas empresas: mitos y realidades',
    category: 'Automatizacion',
    slug: 'automatizacion-pymes',
    readTime: 7,
    excerpt: '"Eso es solo para empresas grandes" o "va a dejar a gente sin trabajo". Cinco mitos sobre automatizacion.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'seo-2026',
    title: 'SEO en 2026: lo que funciona y lo que ya no',
    category: 'SEO',
    slug: 'seo-2026',
    readTime: 7,
    excerpt: 'Si todavia crees que el SEO es "poner palabras clave y esperar", tengo una noticia: Google ya no busca keywords, busca respuestas.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'funnel-digital',
    title: 'De cero a cliente: el funnel digital que todo negocio deberia tener',
    category: 'Estrategia',
    slug: 'funnel-digital',
    readTime: 8,
    excerpt: 'Un funnel no es un embudo que atrapa gente. Es un camino que acompaña decisiones.',
    date: 'Julio 2026',
    published: true,
  },
  {
    id: 'ia-contenido',
    title: 'El poder del contenido generado por IA (sin que parezca IA)',
    category: 'Contenido',
    slug: 'ia-contenido',
    readTime: 7,
    excerpt: 'La IA escribe en segundos, pero suena a robot. El secreto no esta en la herramienta. Esta en el proceso.',
    date: 'Julio 2026',
    published: true,
  },
]


export type Article = typeof articles[0]
